name: EnchantmentGems
author: Smc
main: me.auto.eg.main.Main
description: Enchantment Gems
version: 1.0
depend: [GUI-API, ItemNBTAPI,  ArmorEquipEvent, PermissionsEx, KeepItems]
softdepend: [mcMMO]
api-version: 1.13
commands:
    eg:
        usage: /<command>
        description: Main command for Enchantment Gems.
    sudoku:
        usage: /<command>
        description: Commit sudoku at will.
    trash:
        usage: /<command>
        description: Open a trash GUI.